# sites params
#V_HOSTNAME=v50
#V_PORT=9191
V_HOSTNAME=localhost
V_PORT=8080

V_UNIXUSER=oracle
V_UNIXGROUP=oracle
V_UNIXUSERHOME=/home/oracle
V_INSTALLDIR=/u00
V_SITES_INSTALLDIR=$V_INSTALLDIR/sites
V_SITES_SHAREDDIR=$V_INSTALLDIR/Shared
V_TOMCAT_INSTALLDIR=$V_INSTALLDIR/tomcat
V_JDK_INSTALLDIR=$V_INSTALLDIR/jdk
V_SITES_PATCHLEVEL=patch11

# vagrant params
VAGRANT_LOG=info
VAGRANT_LOGFILE=vagrant.log
V_KITS_DIRECTORY=C:/Users/pgleghor/MEGATRON/kits
V_IP_ADDRESS=192.168.1.150
V_VAGRANT_SSHPORT=2345
V_VAGRANT_MEMORY=1024
V_VAGRANT_GUI=false
