FROM pgleghorn/rsspatch:latest
MAINTAINER pgleghorn@gmail.com
# refresh the scripts and config
ARG V_SCRIPTS
ARG V_CONFIG
ENV V_SCRIPTS=$V_SCRIPTS V_CONFIG=$V_CONFIG
COPY config.sh $V_CONFIG
COPY scripts $V_SCRIPTS
# run
CMD bash -l -c "catalina.sh run"
