FROM wcsbase:latest
MAINTAINER pgleghorn@gmail.com
ARG V_SCRIPTS
ARG V_CONFIG
# refresh scripts
COPY config.sh $V_CONFIG
COPY scripts $V_SCRIPTS
# install sites
RUN $V_SCRIPTS/wcsinstall.sh
CMD /bin/bash -l
