FROM wcsinstall:latest
MAINTAINER pgleghorn@gmail.com
ARG V_SCRIPTS
ARG V_CONFIG
# refresh scripts
COPY config.sh $V_CONFIG
COPY scripts $V_SCRIPTS
# install patch
RUN $V_SCRIPTS/patch11/wcspatchinstall.sh
CMD /bin/bash -l
