#!/bin/sh

SEDEXPR=${1:?sed expression}
FILENAME=${2:?filename}
TMPFILENAME=/tmp/diffsed$$.tmp

if [ -e $FILENAME ]; then
	echo $FILENAME
	cp $FILENAME /tmp/diffsed$$.tmp
	sed -i -e "$SEDEXPR" $FILENAME
	diff $TMPFILENAME $FILENAME
	rm $TMPFILENAME
else
	echo File $FILENAME does not exist or not readable
fi
